title: Apache BookKeeper&trade;
subtitle: A scalable, fault-tolerant, and low-latency storage service optimized for real-time workloads
github_repo: https://github.com/apache/bookkeeper
github_master: https://github.com/apache/bookkeeper/tree/master
permalink: pretty
baseurl: /
destination: local-generated
twitter_url: https://twitter.com/asfbookkeeper

versions:
- "4.10.0"
- "4.9.2"
- "4.9.1"
# [next_version_placeholder]
- "4.9.0"
- "4.8.2"
- "4.8.1"
- "4.8.0"
- "4.7.3"
- "4.7.2"
- "4.7.1"
- "4.7.0"
- "4.6.2"
- "4.6.1"
- "4.6.0"
- "4.5.1"
- "4.5.0"
archived_versions:
- "4.4.0"
- "4.3.2"
- "4.3.1"
- "4.3.0"
- "4.2.4"
- "4.2.3"
- "4.2.2"
- "4.2.1"
- "4.2.0"
- "4.1.0"
- "4.0.0"
latest_version: "4.11.0-SNAPSHOT"
latest_release: "4.10.0"
stable_release: "4.9.2"
eol_releases:
- "4.7.3"
- "4.7.2"
- "4.7.1"
- "4.7.0"
- "4.6.2"
- "4.6.1"
- "4.6.0"
- "4.5.1"
- "4.5.0"
- "4.4.0"
- "4.3.2"
- "4.3.1"
- "4.3.0"
- "4.2.4"
- "4.2.3"
- "4.2.2"
- "4.2.1"
- "4.2.0"
- "4.1.0"
- "4.0.0"
distributedlog_version: "4.10.0"

defaults:
- scope:
    path: docs
  values:
    layout: docs
    toc: true
- scope:
    path: bps
  values:
    layout: community
- scope:
    path: community
  values:
    layout: community
- scope:
    path: project
  values:
    layout: community
- scope:
    path: releases
  values:
    layout: community

gems:
- jekyll-toc

exclude:
- Gemfile
- Gemfile.lock
- Makefile
- vendor/bundle
- local-generated
- generated_site
- scripts
- overview
- README.md

