#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Bookie Tests

on:
  push:
  pull_request:
    branches:
      - master
      - branch-*
    workflow_dispatch:

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

jobs:
  test:
    name: Bookie Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tune Runner VM
        uses: ./.github/actions/tune-runner-vm

      - name: Detect changed files
        id: changes
        uses: apache/pulsar-test-infra/paths-filter@master
        with:
          filters: |
            site3:
              - 'site3/**'

      - name: Cache local Maven repository
        if: steps.changes.outputs.site3 != 'true'
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/apache/bookkeeper
            !~/.m2/repository/org/apache/distributedlog
          key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 11
        if: steps.changes.outputs.site3 != 'true'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Maven build bookkeeper-server
        if: steps.changes.outputs.site3 != 'true'
        run: mvn -B -nsu -am -pl bookkeeper-server clean install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO

      - name: Run bookie tests
        if: steps.changes.outputs.site3 != 'true'
        run: mvn -B -nsu -pl bookkeeper-server test -Dtest="org.apache.bookkeeper.bookie.**" -DfailIfNoTests=false -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO

      - name: Run shell tests
        if: steps.changes.outputs.site3 != 'true'
        run: mvn -B -nsu -pl tests/scripts install -DfailIfNoTests=false -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO

      - name: Aggregates all test reports to ./test-reports and ./surefire-reports directories If failure
        if: failure()
        continue-on-error: true
        uses: ./.github/actions/copy-test-reports

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v3
        if: failure()
        continue-on-error: true
        with:
          name: bookie-tests-reports
          path: surefire-reports

      - name: print JVM thread dumps when cancelled
        if: cancelled()
        run: ./dev/ci-tool print_thread_dumps
