name: Bot tests
on:
  issue_comment:
    types: [created]

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bot actions
        uses: zymap/bot@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.BKBOT_TOKEN }}
        with:
          repo_owner: apache
          repo_name: bookkeeper
          rerun_cmd: rerun failure checks
          comment: ${{ github.event.comment.body }}
